### ISSUE TITLE
CSS includes not compiling into css/mnml.css

### ISSUE THREAD

**Issue by okayjeffrey** [mrmrs/mnml#25]
No error before the new update, but after updated code. I am receiving this error.

```
/Users/okayjeffrey/Development/mnml-theme/node_modules/node-minify/lib/node-minify.js:104
          throw new Error(bin + ' not found !');
          ^

Error: sqwish not found !
    at getPath (/Users/okayjeffrey/Development/mnml-theme/node_modules/node-minify/lib/node-minify.js:104:17)
    at Object.minify.fn.compress (/Users/okayjeffrey/Development/mnml-theme/node_modules/node-minify/lib/node-minify.js:137:27)
    at Object.minify (/Users/okayjeffrey/Development/mnml-theme/node_modules/node-minify/lib/node-minify.js:83:10)
    at Object.<anonymous> (/Users/okayjeffrey/Development/mnml-theme/index.js:30:1)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
[BS] File changed: css/mnml.css
```

*Please note I am a noob to Node so I don't know how to search out* **sqwish**

**Comment by okayjeffrey** [comment]
To clarify I installed sqwish per requirement I went back and saw in the install log
```
~/Development/mnml-theme  ☠ npm install -g sqwish@0.2.2
/usr/local/bin/sqwish -> /usr/local/lib/node_modules/sqwish/bin/sqwish
/usr/local/lib
└── sqwish@0.2.2 
```

I still receive the same error when changing files. :/

**Comment by okayjeffrey** [comment]
**Found fix is with node-minify 1.3.7**
*Reverting to 1.3.2 fixed this issue.*
https://github.com/srod/node-minify/issues/81

**Comment by xiaogwu** [comment]
Experiencing same issue after node-minify was updated to 1.3.7.  Reverting to 1.3.2 resolved the issue.  I think we should revert PR#28.

**Comment by mattcdowning** [comment]
@xiaogwu Not sure why updating to node-minify 1.3.7 fixed my issue initially. I've tested it again and experienced the same issue as you and @okayjeffrey (apologies for causing any headaches!). Instead of reverting back to 1.3.2, however, I've found that running `npm update` from within the node-minify folder also fixes the issue (yet it does then warn that lodash@<3.0.0 is no longer maintained and to upgrade to lodash@^4.0.0). 
I suppose reverting [PR#28](https://github.com/mrmrs/mnml/pull/28) would be better to avoid the extra step of updating node-minify. My question though is, would finding a way to move the project forward in terms of updated dependencies (for whatever benefits those might bring) be more useful than reverting to where it "just works"? For example, running `npm outdated` indicated that postcss-import and watch are not at the latest versions. Would it be helpful to find a way to update those as well?
